language: ruby
rvm:
- 2.4.2
cache: bundler
gemfile: docs/Gemfile
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - gem update --system
  - gem install bundler

install:
  - gem install jekyll
  - gem install html-proofer

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
    - master
