language: ruby
rvm:
- 2.4
cache: bundler
gemfile: docs/Gemfile
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
    - master